name: Main CI

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    name: Build for main
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --tag jeroeng/rustywind:dev
    - name: Push to Docker Hub
      if: github.event_name != 'pull_request'
      run: docker login -u="jeroeng" -p="${{ secrets.DOCKERHUB_TOKEN }}" && docker push jeroeng/rustywind:dev