name: PR CI

on:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    name: Build for Pull Request
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --tag jeroeng/rustywind:test